project:
  type: website
  output-dir: docs

website:
  title: "Introdução ao R"
  navbar:
    left:
      - href: index.qmd
        text: Página inicial
      - href: about.qmd
        text: Sobre o curso

format:
  html:
    theme: simplex
    css: styles.css
    toc: false



