---
title: "Aulas e laboratórios"
lang: pt-br
---

Abaixo, estão listados os links de acesso aos slides, códigos dos
slides, scripts em R e gravações das aulas e laboratórios
relacionados a cada tópico do curso.
Os materiais descritos nesta página são mantidos
pelo autor Bruno Montezano.

## Aula 1: R e RStudio

* [Slides](slides/1_r_e_rstudio/slides_r_e_rstudio.html)
* [Código dos slides](https://raw.githubusercontent.com/brunomontezano/r-workshop/main/slides/1_r_rstudio/slides_r_e_rstudio.qmd)
* [Script em R](https://raw.githubusercontent.com/brunomontezano/r-workshop/main/slides/1_r_e_rstudio/script_r_e_rstudio.R)
* [Gravação da aula](https://youtu.be/MhysI-QdtZY)
* [Gravação do laboratório](https://youtu.be/DhosKMrXevY)
  
## Aula 2: Manipulação de dados

* [Slides](slides/2_manipulacao/slides_manipulacao.html)
* [Código dos slides](https://raw.githubusercontent.com/brunomontezano/r-workshop/main/slides/2_manipulacao/slides_manipulacao.qmd)
* [Script em R](https://raw.githubusercontent.com/brunomontezano/r-workshop/main/slides/2_manipulacao/script_manipulacao.R)
* [Gravação da aula](https://youtu.be/EpWgpzLWxJ8)
* [Gravação do laboratório](https://youtu.be/tntHJWTlR3o)
* [Arquivo `gambas.csv`](https://drive.google.com/uc?export=download&id=1BQgajup9B7MKJxSSrW0_x_GCrDuCkrjj)
  
## Aula 3: Visualização de dados
  
* [Slides](slides/3_visualizacao/slides_visualizacao.html)
* [Código dos slides](https://raw.githubusercontent.com/brunomontezano/r-workshop/main/slides/3_visualizacao/slides_visualizacao.qmd)
* [Script em R](https://raw.githubusercontent.com/brunomontezano/r-workshop/main/slides/3_visualizacao/script_visualizacao.R)
* [Gravação da aula](https://youtu.be/wMcOUMCv5NM)
* [Arquivo `dados_psiquiatria.sav`](https://drive.google.com/uc?export=download&id=1CbXFwWPbSChEbYlj2b6k6LEEf6xsT4VG)
* [Arquivo `dados_antropometricos.xlsx`](https://drive.google.com/uc?export=download&id=1MyePYTxHybfbQ75LIXyJgKDbRAtvQdT2)
  
## Aula 4: Análise descritiva
  
* [Slides](slides/4_descritiva/slides_descritiva.html)
* [Código dos slides](https://raw.githubusercontent.com/brunomontezano/r-workshop/main/slides/4_descritiva/slides_descritiva.qmd)
* [Script em R](https://raw.githubusercontent.com/brunomontezano/r-workshop/main/slides/4_descritiva/script_descritiva.R)
* [Gravação da aula](https://youtu.be/a9-yo5IwC84)

## Aula 5: Inferência estatística
  
* [Slides](slides/5_inferencia/slides_inferencia.html)
* [Código dos slides](https://raw.githubusercontent.com/brunomontezano/r-workshop/main/slides/5_inferencia/slides_inferencia.qmd)
* [Script em R](https://raw.githubusercontent.com/brunomontezano/r-workshop/main/slides/5_inferencia/script_inferencia.R)
  
## Aula 6: Modelos de regressão
  
* [Slides](slides/6_regressao/slides_regressao.html)
* [Código dos slides](https://raw.githubusercontent.com/brunomontezano/r-workshop/main/slides/6_regressao/slides_regressao.qmd)
* [Script em R](https://raw.githubusercontent.com/brunomontezano/r-workshop/main/slides/6_regressao/script_regressao.R)
  
## Aula 7: Tópicos avançados
  
* [Slides](slides/7_topicos_avancados/slides_topicos_avancados.html)
* [Código dos slides](https://raw.githubusercontent.com/brunomontezano/r-workshop/main/slides/7_topicos_avancados/slides_topicos_avancados.qmd)
* [Script em R](https://raw.githubusercontent.com/brunomontezano/r-workshop/main/slides/7_topicos_avancados/script_topicos_avancados.R)

