---
title: "Perguntas frequentes"
lang: pt-br
---

## Quem é o público alvo?

O público-alvo deste curso de introdução ao R para análises nas ciências da
saúde é composto principalmente por psiquiatras, psicólogos e outros
profissionais de saúde que desejam aprender a utilizar ferramentas de análise de
dados para suas pesquisas e práticas clínicas. O curso é voltado tanto para
iniciantes em programação quanto para aqueles que já possuem algum conhecimento
prévio em R, mas desejam aprimorar suas habilidades e aprender novas técnicas
para análise de dados.

## Onde serão as aulas?

As aulas se darão em formato virtual. As aulas serão
serão realizadas através de videoconferências na plataformas Google Meet
para os integrantes do grupo de pesquisa Alliance, ministradas pelo
psicólogo e mestrando Bruno Montezano.

## Quantas aulas serão realizadas?

O plano de aulas seguirá as seguintes aulas:

1. R e RStudio
2. Manipulação de dados
3. Visualização de dados
4. Análise descritiva
5. Análise inferencial
6. Modelos de regressão
7. Tópicos avançados

Ou seja, realizaremos sete aulas com duração entre 45 minutos e 1 hora.

## O código-fonte do site do curso é disponibilizado?

Sim, você pode acessar o [repositório do curso no GitHub](https://github.com/brunomontezano/r-workshop), onde estão contidos todos
os códigos, dados e slides do curso.

## Que %#$&! Não consegui completar o exercício $x$! Isso não é para mim!

O aprendizado de programação e análise de dadosé uma jornada árdua porque muitas
vezes nos deparamos com conceitos e conteúdos que nunca estudamos antes. O fator
mais importante no êxito nessa caminhada é persistir e saber como buscar ajuda.

No contexto do curso, vocês podem enviar um email para solicitar ajuda, serão
muito bem-vindos! O endereço é
[bmontezano@hcpa.edu.br](mailto:bmontezano@hcpa.edu.br). Alguns sites bons de
conhecer para buscar dúvidas ou solucionar problemas específicos são o
[Stack Overflow](https://stackoverflow.com/questions/tagged/r) e a
[Posit Community](https://community.rstudio.com/) (antiga RStudio Community).
Nestes fóruns, os usuários de R publicam dúvidas, perguntas, problemas e soluções
para diferentes tipos de rotinas de análise e manipulação de dados. Você pode
criar sua conta e fazer você mesmo suas perguntas também!

## Qual o cronograma de aulas? O curso terá laboratórios?

Segue abaixo o cronograma de aulas do curso:

1. R e RStudio (17/04/2023)
2. Manipulação de dados (24/04/2023)
3. Visualização de dados (08/05/2023)
4. Análise descritiva (15/05/2023)
5. Inferência estatística (22/05/2023)
6. Modelos de regressão (29/05/2023)
7. Tópicos avançados (05/06/2023)

Em relação aos laboratórios, eles acontecerão no sábado da semana
da aula correspondente. Assim como as aulas, os laboratórios serão
gravados e disponibilizados no site do curso.

## O curso possui algum pré-requisito?

O curso não possui pré-requisitos obrigatórios. No entanto, é recomendável que
os participantes tenham conhecimento básico em estatística e experiência prévia
em análise de dados. Além disso, é importante que os participantes possuam
conhecimento básico em informática.