---
title: "Gabarito da Aula 7: Introdução ao aprendizado de máquina"
lang: pt-br
code-annotations: select
---

## Dica de leitura: [An Introduction to Statistical Learning](https://www.statlearning.com/)

Este livro é um dos melhores materiais para aprender aprendizado de máquina.
O livro traz diversos exemplos em R além de explicar algumas bases estatísticas
de forma didática com aplicações práticas. Recomendo que você leia!
O engenheiro de software Emil Hvitfeldt solucionou os laboratórios do livro
utilizando o *framework* do `tidymodels` ([você pode acessar aqui o site](https://emilhvitfeldt.github.io/ISLR-tidymodels-labs/index.html)).

## Rodar os códigos dos slides para tentar reproduzir o exemplo

O código pode ser acessado [através deste link](https://raw.githubusercontent.com/brunomontezano/r-workshop/main/slides/7_intro_ml/slides_intro_ml.qmd).
Você deve ter o pacote `tidymodels` instalado no seu R para ser capaz de
rodar o exemplo dado em aula. Você pode instalar o pacote da seguinte forma:

```{r instalar-tidymodels}
#| eval: false
install.packages("tidymodels")
```

Aproveite para mudar os argumentos das funções e observar quais mudanças acontecem,
é um bom exercício!